dankomiocevic/ghoti

internal/slots/slots.go
Just some code cleanup to add new commands.
=> Split slots into different files

internal/slots/memory.go, internal/slots/timeout.go
I missed to add these files on the previous PR: https://github.com/dankomiocevic/ghoti/pull/5
=> Add missing files

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/integration_test.go, internal/cluster/join_server.go, internal/cluster/join_server_test.go, internal/cluster/membership_manager.go, internal/cluster/membership_manager_test.go
This PR is adding some integration tests for the cluster:
- Test a cluster with 3 nodes.
- Remove the leader node from the cluster and verify someone else takes its place.
Adds the missing join call.
=> Increase coverage and fixes for cluster

internal/config/config.go, internal/config/config_test.go
Adding some tests for the configuration loading, more specifically on the cluster configuration. Also fixed some issues found with tests.
=> Increase coverage and fixes for config

cmd/benchmark/benchmark.go, internal/errors/README.md, internal/errors/errors.go, internal/errors/errors_test.go
This PR is adding a package to handle the error codes that the application will be using.
=> Add error codes

internal/auth/auth.go, internal/config/config_test.go, internal/errors/README.md, internal/errors/errors.go, internal/errors/errors_test.go, internal/server/server.go, internal/server/server_test.go
Migrated the generic error responses to the ones defined in the internal errors package.
These responses have an error code that can help identify the specific problem with the request.
=> Change generic errors to specific

cmd/run/run.go, config.yaml, internal/config/config.go
Adding the configuration options to set logging level and logging format.
=> Add log configuration

internal/config/config_test.go
Adding more tests for the logging configuration.
=> Add tests for logging config

go.mod, go.sum, internal/server/connection.go, internal/server/connection_manager.go, internal/server/server.go
Adding a connection manager to handle the list of active connections.
=> Gracefully close connections

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/join_server.go
- Adds logs to cluster
- Adds proper shutdown to join server
=> Add logs to cluster

cmd/run/run.go, config.yaml, internal/cluster/empty_cluster.go, internal/cluster/join_server.go, internal/server/message.go, internal/server/server.go, internal/server/server_test.go
Only the Leader node can receive calls, the other nodes will return an error if there is a call made to them.
=> Do not allow calls to followers

cmd/run/run.go, internal/config/config.go, internal/config/config_test.go
=> Improve coverage

cmd/run/run_test.go
Yeah, I forgot to add this one on the previous PR.
=> Add missing file

cmd/benchmark/benchmark.go, cmd/benchmark/integration_test.go, cmd/version.go, cmd/version_test.go
Add tests for missing commands.
=> Increase coverage

Makefile, README.md, cmd/benchmark/integration_test.go, cmd/run/integration_test.go, internal/cluster/cluster.go, internal/cluster/empty_cluster.go, internal/cluster/integration_test.go, internal/cluster/join_server.go, internal/cluster/membership_manager_test.go
Add option to remove a node from the cluster.
=> Add option to remove node from cluster

internal/cluster/cluster.go, internal/cluster/empty_cluster_test.go, internal/cluster/integration_test.go
=> Adding more coverage

internal/cluster/join_server_test.go
Adding more coverage for the Remove API.
=> Add test for remove method in JoinManager

internal/config/config.go, internal/server/message.go, internal/server/server.go, internal/server/server_test.go
This PR adds support for Telnet protocol that has an extra `\r`.
=> Add telnet support

README.md
This PR adds more details about how telnet protocol can be used and a link to the list of errors that can be returned when there is an issue on the message sent.
=> Add description about Telnet

internal/server/connection.go, internal/server/server.go
Wiring some of the connection writes to use the async path through the events goroutine. There are still paths missing.
=> Using async writes

config.yaml, internal/config/config.go, internal/connection_manager/connection_manager.go, internal/connection_manager/tcp_manager.go, internal/connection_manager/telnet_manager.go, internal/server/server.go, internal/server/server_test.go, internal/slots/broadcast.go, internal/slots/leaky_bucket_test.go, internal/slots/slots.go, internal/slots/ticker_test.go, internal/slots/timeout_test.go, internal/slots/token_bucket_test.go
This change adds the broadcast slot, this slot allows to send a value to all the connected clients.
In order to have this change available, I added some changes to the config.
This change still needs to be thoroughly tested, that will happen in a follow up PR.
=> Add broadcast slot

README.md, internal/connection_manager/tcp_broadcast_test.go
This PR adds a test for the broadcast method.
It also improves the documentation for the broadcast slot.
=> Add broadcast test

README.md
This pull request adds a "Next steps" section to the `README.md` file, outlining planned future improvements for the project.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R368-R378): Added a "Next steps" section listing planned improvements, including WebSocket support, a simpler Cluster implementation, metrics and monitoring, missing slot implementation, performance benchmarking for slots, and Docker support.
=> Add next steps to README.

.github/CODEOWNERS, .github/workflows/pull_request.yaml, .golangci.yaml
This pull request introduces a set of changes to improve code quality, automate workflows, and establish ownership. The changes include adding a new GitHub Actions workflow for pull requests, configuring `golangci-lint` for Go code linting, and assigning ownership of all files to a specific user.
* [`.github/workflows/pull_request.yaml`](diffhunk://#diff-7b2a967de7060a238e49a57908f83e860b8cb53a0b0991c3d0d275857c1014d4R1-R55): Added a new GitHub Actions workflow to automate linting and testing for pull requests. The workflow includes steps for setting up Go, running `golangci-lint`, executing tests, and uploading coverage results to Codecov.
* [`.golangci.yaml`](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R1-R91): Introduced a configuration file for …
=> Add tests and coverage to PRs

docs/index.html
Adding Github pages website to add some tutorials, blog posts and updates.
=> Enable Github Pages
